name: Workflow Trigger Filters
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
   job1:
     runs-on: ubuntu-latest
     steps:
     - name: Print the Trigger Name     
       run: |
          echo "trigger name ${{ github.event_name }}"
          echo "bran
          ch Name is ${{ github.ref_name}}"          
          
          
          